name: main

on:
  push:
    branches:
      - "development"
      - "add-obsolete-action-command"
  
jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Dependency
      working-directory: ./Dashboard
      run: yarn

    - name: Build .env
      working-directory: ./Dashboard
      run: |
        echo "VITE_OBSOLETE_DATA_PATH=$VITE_OBSOLETE_DATA_PATH" >> .env
        echo "VITE_API_PATH=$VITE_API_PATH" >> .env

    - name: Build Dashboard
      working-directory: ./Dashboard
      run: yarn build --outDir ../publish

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
        destination_dir: dashboard